appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: B301tsF0guo9q2BVk2NioHLYdAxOZsYvxzEIDoMtBG3Dm8owwhMYM/ibudVpv9oDBdCtIH6KZn2k3UyJoHTGqXDDm5xjkrYxufxLEyABuO58B74IH25OAXuOx2K8/1QIUZiHnnydwjGw4HYT9J2ZAAps+IPoKJPk7Q8dSZMki3sRaMupBYdfMKij2sQIc66lkeQ686vex0B5HmxJrACKP+Zs6/hxxSnHRqYn6GosSZi2aeNGiezmXQc63DMB+nlNrBwN4nxVYoHNogIab7kPdFtWrToH3Ui4EO7MD0zcNA+Kqsb7vod2OlXZ1Ts8Dry2AKbKI2158hNUjxsBHt/BYKDzJV+zYlWmRMWNJhflSLz8PQrg+euHn98TY9S1fhS6TYMNtBh0gpxtwehRcbgYLNuAZogJrbRKAIwBMj2AmaJT3xOd5gGk3GX2Mm+OGo36Cws+GG36ezJuPzbD3l9xFE6NdhbV3c4OCnvWPTmbndZoKK4mPvTlYvHAYS0ASEVDz6XUBYRhY6ZcVPHpsTGEVTwzJ3iqcbcZKWY7w3E90nelTa7NXG4r2CITYrFCqpsE6yj9Uer4nSz6uzHJwdPyciZuLH5z6ecRIOBGNDUmHxIs/aPBMPh2rgt1mY8x6HKs+wdyviSG12fiQrDfM5dWIPdH1xiQWx4nLyKIS+TaNZ8=
conda_forge_output_validation: true
